### ISSUE TITLE
[2pt] Implement methods for MusicAlbum and Genre classes - Implement methods (Team member 2)

### ISSUE THREAD

**Issue by JonahKayizzi** [JonahKayizzi/My-Catalog-Ruby-Capstone#13]
- add_item method in the Genre class

- [x] should take an instance of the Item class as an input
- [x] should add the input item to the collection of items
- [x] should add self as a property of the item object (by using the correct setter from the item object)

- can_be_archived?() in the MusicAlbum class

- [x] should override the method from the parent class
- [x] should return true if parent's method returns true AND if on_spotify equals true
- [x] otherwise, it should return false

**Comment by eng-mohamed-eldeeb** [comment]
I have done these tasks in the previous card.
