### ISSUE TITLE
Set up a kanban board for the project

### ISSUE THREAD

**Issue by JonahKayizzi** [JonahKayizzi/My-Catalog-Ruby-Capstone#32]
The project tasks have been created and split amongst the 3 team members @JonahKayizzi as Team member 1, @eng-mohamed-eldeeb as Team member 2 and @rebaz36  as Team member 3 

- The project can be found [here](https://github.com/users/JonahKayizzi/projects/5)

**Comment by prolajumokeoni** [comment]
Hi @Team

Your project board setup is complete!  Wishing you all  the best with your Capstone project

Congratulations! 🎉 

## Highlights

- Amazing project board setup 👏🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
